In [2]:
import pandas as pd

from pandas import Series,DataFrame

# pandas的数据结构

## series

In [3]:
obj= pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2=pd.Series([4, 7, -5, 3],index=['a','b','c','d'])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [10]:
obj2['a']
obj2[obj2>0]

a    4
b    7
d    3
dtype: int64

In [11]:
obj2*2

a     8
b    14
c   -10
d     6
dtype: int64

In [12]:
import numpy as np
np.exp(obj2)

a      54.598150
b    1096.633158
c       0.006738
d      20.085537
dtype: float64

In [17]:
sdata={'Ohio':35000,'Texas':710000,'Utah':50000,'Oregon':16000}
obj3=pd.Series(sdata)
obj3

Ohio       35000
Texas     710000
Utah       50000
Oregon     16000
dtype: int64

In [22]:
states=['California','Oregon','Ohio','Texas']
obj4 =pd.Series(sdata,index=states)
obj4

California         NaN
Oregon         16000.0
Ohio           35000.0
Texas         710000.0
dtype: float64

In [23]:
pd.isnull(obj4)

California     True
Oregon        False
Ohio          False
Texas         False
dtype: bool

In [24]:
pd.notnull(obj4)

California    False
Oregon         True
Ohio           True
Texas          True
dtype: bool

In [25]:
obj4.isnull()

California     True
Oregon        False
Ohio          False
Texas         False
dtype: bool

In [26]:
obj3+obj4

California          NaN
Ohio            70000.0
Oregon          32000.0
Texas         1420000.0
Utah                NaN
dtype: float64

In [28]:
obj4.name='population'
obj4.index.name='state'
obj4

state
California         NaN
Oregon         16000.0
Ohio           35000.0
Texas         710000.0
Name: population, dtype: float64

In [29]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [33]:
obj.index=states
obj

California    4
Oregon        7
Ohio         -5
Texas         3
dtype: int64

## DataFrame

建DataFrame的办法有很多，最常用的是一种直接传入一个等长列表或numpy组成的字典

In [38]:
data={'state':['Ohio','Ohio','Ohio','Nevada','Nevada',
               'Nevada'],
     'year':[2000,2001,2002,2001,2002,2003],
     'pop':[1.5,1.7,3.6,2.4,2.9,3.2]
     }
frame=pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [39]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [53]:
frame=pd.DataFrame(data,columns=[ 'year','state','pop','debt'],
            index=['one','two','three','four','five','six'])

In [46]:
frame['debt']=16.5
frame

state  year  pop  debt
0    Ohio  2000  1.5  16.5
1    Ohio  2001  1.7  16.5
2    Ohio  2002  3.6  16.5
3  Nevada  2001  2.4  16.5
4  Nevada  2002  2.9  16.5
5  Nevada  2003  3.2  16.5

In [48]:
frame['debt']=np.arange(6)
frame

state  year  pop  debt
0    Ohio  2000  1.5     0
1    Ohio  2001  1.7     1
2    Ohio  2002  3.6     2
3  Nevada  2001  2.4     3
4  Nevada  2002  2.9     4
5  Nevada  2003  3.2     5

In [54]:
val=pd.Series([-1.5,-1.3,-1.7],
              index=["two","four","five"])
frame["debt"]= val
frame

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.5
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.3
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [57]:
frame["eastern"]=frame.state=="Ohio"
frame

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.5     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.3    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [60]:
frame.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [63]:
pop={'navada':{2001:2.4,2002:2.9},
    "ohio":{2000:1.5, 2001:1.7, 2002:3.6}}
frame3=pd.DataFrame(pop)
frame3

navada  ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [64]:
frame3.T

2000  2001  2002
navada   NaN   2.4   2.9
ohio     1.5   1.7   3.6

In [65]:
pd.DataFrame(pop,index=[2001,2002,2003])

navada  ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

## 索引对象

In [68]:
obj= pd.Series(range(3), index=['a', 'b', 'c'])
index= obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [69]:
index[1]

'b'

In [72]:
labels= pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [76]:
frame3

navada  ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [78]:
frame3.columns

Index(['navada', 'ohio'], dtype='object')

In [79]:
dup_labels= pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [80]:
obj= pd.Series(range(3), index=['a', 'b', 'c'])
index= obj.index

index.append(index)

Index(['a', 'b', 'c', 'a', 'b', 'c'], dtype='object')

In [81]:
index.difference(index)

Index([], dtype='object')

In [82]:
index.intersection(index)

Index(['a', 'b', 'c'], dtype='object')

In [83]:
index.union(index)

Index(['a', 'b', 'c'], dtype='object')

# 重新索引

In [84]:
obj=pd.Series([4.5, 7.2, -5.3, 3.6],
             index=['d','b', 'a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [88]:
obj2=obj.reindex(['a', 'b', 'c', 'd','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [90]:
obj3=pd.Series(['blue','purple', 'yellow'],
               index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [93]:
obj3.reindex(range(6),
           method='pad')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [101]:
frame=pd.DataFrame(np.arange(9).reshape(3, 3),
                   index=['a', 'b','c'],
                   columns=['ohio', 'texas','california'])
frame
                   

ohio  texas  california
a     0      1           2
b     3      4           5
c     6      7           8

In [97]:
frame2=frame.reindex(['a','b','c','d'])
frame2

ohio  texas  califonia
a   0.0    1.0        2.0
b   3.0    4.0        5.0
c   6.0    7.0        8.0
d   NaN    NaN        NaN

In [102]:
states=["texas",'utah','california']
frame.reindex(columns=states)

texas  utah  california
a      1   NaN           2
b      4   NaN           5
c      7   NaN           8

# 丢弃指定轴上的项

In [104]:
obj=pd.Series(np.arange(5),
             index=["a",'b','c','d','e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [106]:
new_obj=obj.drop('c')
new_obj

a    0
b    1
d    3
e    4
dtype: int32

In [107]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),
                 index=(1, 2, 3, 4),
                 columns=[1, 2, 3, 4])
data



1   2   3   4
1   0   1   2   3
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15

In [108]:
data.drop([1,2])

1   2   3   4
3   8   9  10  11
4  12  13  14  15

In [109]:
data.drop(3,axis=1)

1   2   4
1   0   1   3
2   4   5   7
3   8   9  11
4  12  13  15

In [110]:
## 索引、选取和过滤

In [115]:
obj=pd.Series(np.arange(5,9),index=[1,2, 3, 4])
obj

1    5
2    6
3    7
4    8
dtype: int32

In [116]:
obj[3]

7

In [121]:
data.index=['a','c','b','s']
data.columns=['hello','wo','ku','le']
data

hello  wo  ku  le
a      0   1   2   3
c      4   5   6   7
b      8   9  10  11
s     12  13  14  15

In [123]:
data['hello']

a     0
c     4
b     8
s    12
Name: hello, dtype: int32

In [124]:
data[:2]

hello  wo  ku  le
a      0   1   2   3
c      4   5   6   7

In [126]:
data['ku']> 5

a    False
c     True
b     True
s     True
Name: ku, dtype: bool

In [127]:
data[data['ku']> 5]

hello  wo  ku  le
c      4   5   6   7
b      8   9  10  11
s     12  13  14  15

## 用loc和iloc进行选取

In [129]:
data

hello  wo  ku  le
a      0   1   2   3
c      4   5   6   7
b      8   9  10  11
s     12  13  14  15

In [130]:
data.loc['a',['hello','wo']]

hello    0
wo       1
Name: a, dtype: int32

In [131]:
data.iloc[2,[3,0,1]]

le       11
hello     8
wo        9
Name: b, dtype: int32

In [132]:
data.iloc[2]

hello     8
wo        9
ku       10
le       11
Name: b, dtype: int32

In [133]:
data.iloc[[1,2],[0,1,2]]

hello  wo  ku
c      4   5   6
b      8   9  10

In [134]:
data.iloc[:2,[2,3]]

ku  le
a   2   3
c   6   7

## 整数索引

In [142]:
ser=pd.Series(np.arange(3))
ser
ser[-1]

KeyError: -1

In [141]:
ser2=pd.Series(np.arange(3.),index=['a','b','c'])
ser2
ser2[-1]

2.0

In [143]:
ser[:1]

0    0
dtype: int32

In [144]:
ser.loc[:1]

0    0
1    1
dtype: int32

# 算数运算和数据对齐

In [149]:
sl1= pd.Series([7.3, -2.5, 3.4,1.5],
             index=['a','b','c','d'])

sl2= pd.Series([7.3,-2.5,3.4,1,5],
             index=['a','b','c','d','e'])
sl

a    7.3
b   -2.5
c    3.4
d    1.5
dtype: float64

In [150]:
sl1+sl2

a    14.6
b    -5.0
c     6.8
d     2.5
e     NaN
dtype: float64

In [151]:
sl1.add(sl2,fill_value=0)

a    14.6
b    -5.0
c     6.8
d     2.5
e     5.0
dtype: float64

In [152]:
df1=pd.DataFrame(np.arange(9.).reshape((3,3)),
                index=['hello','wo','si'])
df2=pd.DataFrame(np.arange(12.).reshape((4,3)),
                index=['hello','wo','si','le'])
df1+df2

0     1     2
hello   0.0   2.0   4.0
le      NaN   NaN   NaN
si     12.0  14.0  16.0
wo      6.0   8.0  10.0

In [154]:
df1.add(df2,fill_value=0)

0     1     2
hello   0.0   2.0   4.0
le      9.0  10.0  11.0
si     12.0  14.0  16.0
wo      6.0   8.0  10.0

In [155]:
1/df1

0         1      2
hello       inf  1.000000  0.500
wo     0.333333  0.250000  0.200
si     0.166667  0.142857  0.125

In [156]:
df1.sub(df2,fill_value=0)

0     1     2
hello  0.0   0.0   0.0
le    -9.0 -10.0 -11.0
si     0.0   0.0   0.0
wo     0.0   0.0   0.0

In [157]:
df1.div(df2,fill_value=0)

0    1    2
hello  NaN  1.0  1.0
le     0.0  0.0  0.0
si     1.0  1.0  1.0
wo     1.0  1.0  1.0

## DataFrame和Series之间的运算

In [161]:
arr=np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [159]:
arr[0]

array([0., 1., 2., 3.])

In [160]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [166]:
frame=pd.DataFrame(np.arange(12.).reshape((4,3)),
                  columns=list('bde'),
                  index=['wo','si','le','a'])
series=frame.iloc[0]

frame


b     d     e
wo  0.0   1.0   2.0
si  3.0   4.0   5.0
le  6.0   7.0   8.0
a   9.0  10.0  11.0

In [170]:
series
series2=pd.Series(range(3),index=['b','c','e'])
print(series2)

b    0
c    1
e    2
dtype: int64


In [164]:
frame-series

b    d    e
wo  0.0  0.0  0.0
si  3.0  3.0  3.0
le  6.0  6.0  6.0
a   9.0  9.0  9.0

## 函数应用和映射

In [172]:
frame=pd.DataFrame(np.random.randn(4,3),columns=list('bde'),
                  index=['wo','si','le','a'])
frame

b         d         e
wo -0.756981  1.453896  1.510077
si -0.031588  0.725782  1.187028
le -0.653468 -0.052755 -0.282882
a   0.034016 -1.510201 -1.243955

In [173]:
np.abs(frame)

b         d         e
wo  0.756981  1.453896  1.510077
si  0.031588  0.725782  1.187028
le  0.653468  0.052755  0.282882
a   0.034016  1.510201  1.243955

In [176]:
f=lambda x: x.max()-x.min()
frame.apply(f)

b    0.790997
d    2.964097
e    2.754033
dtype: float64

In [178]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])
frame.apply(f)

b         d         e
min -0.756981 -1.510201 -1.243955
max  0.034016  1.453896  1.510077

In [179]:
format=lambda x:'%.2f' %x
frame.applymap(format)

b      d      e
wo  -0.76   1.45   1.51
si  -0.03   0.73   1.19
le  -0.65  -0.05  -0.28
a    0.03  -1.51  -1.24

## 排序和排名

In [180]:
obj=pd.Series(range(4),index=['a','s','b','c'])
obj.sort_index()

a    0
b    2
c    3
s    1
dtype: int64

In [182]:
frame=pd.DataFrame(np.arange(8).reshape((2,4)),
                  index=['three','one'],
                  columns=['d','a','b','c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [184]:
obj=pd.Series([1, 7, -3, 2])
obj.sort_values()

2   -3
0    1
3    2
1    7
dtype: int64

In [186]:
obj=pd.Series([4,np.nan,7, np.nan, -3,2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [187]:
frame=pd.DataFrame({"b":[4,7,-3,2],"a":[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [188]:
frame.sort_values(by="b")

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [189]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [190]:
obj=pd.Series([7, -5, 7,4,2,0,4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [191]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [192]:
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [199]:
frame= pd.DataFrame({'b':[4.2,7,-3,2],'a':[0,1,0,1],
                   "c":[-2, 5,8,-2.5]})
frame


b  a    c
0  4.2  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [200]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

## 带有重复标签的轴索引

In [201]:
obj=pd.Series(range(5),index=['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [202]:
obj.index.is_unique

False

In [203]:
obj['a']

a    0
a    1
dtype: int64

In [204]:
df=pd.DataFrame(np.random.randn(4,3),
                index=['a','a','b','b'])
df

0         1         2
a -1.365259  0.799196 -1.192743
a  1.376570 -0.014422 -0.594849
b -1.557873  0.021101 -1.729667
b  0.270554 -0.588019  0.572712

In [205]:
df.loc['b']

0         1         2
b -1.557873  0.021101 -1.729667
b  0.270554 -0.588019  0.572712

# 汇总和计算描述统计

In [208]:
df= pd.DataFrame([1.4,np.nan],[7.1,-4.5],
                [np.nan,np.nan],[0,75,-1.3],
                 index=['a','b','c','d'],
                 columns=['one','two'])
df

TypeError: __init__() got multiple values for argument 'index'

## 相关系数和协方差

In [207]:
return.corr()

return.cov()

return.corrwith()

SyntaxError: invalid syntax (<ipython-input-207-e85079d9f166>, line 1)

## 唯一值、值计数 以及成员资格

In [213]:
obj=pd.Series([1, 1,1, 1,2,2,2,2])
unique=obj.unique()
unique

array([1, 2], dtype=int64)

In [214]:
obj.value_counts()

2    4
1    4
dtype: int64

In [217]:
pd.value_counts(obj.values,sort=False)

1    4
2    4
dtype: int64

In [219]:
mask=obj.isin([1,3])
mask

0     True
1     True
2     True
3     True
4    False
5    False
6    False
7    False
dtype: bool

In [220]:
obj[mask]

0    1
1    1
2    1
3    1
dtype: int64